default: &default
  adapter: postgresql
  encoding: utf8
  host: db
  username: postgres
  password:
  pool: 5

development:
  <<: *default
  database: silver_development

test:
  <<: *default
  database: silver_test
